"""
Shared in-process report store.

In production this would be a Delta table lookup via Databricks SQL.
For local dev and CI, reports generated by /chat are held here so /reports can serve them.

Keys: report_id (== session_id from AgentState)
Values: raw report dict from report_writer agent
"""

_report_store: dict[str, dict] = {}
